apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: cns-bucket-instance
  namespace: test-ns
spec:
  serviceClassName: cns-bucket-service
  planName: default
  parameters:
    bucketName: "cns-bucket-demo" # Optional
